strtab  1  "The end of the world is our playground."
strtab  2  "The company is family. The family is the company."
strtab  3  "Escape the mundane. Embrace the extraordinary."
strtab  4  "Work hard, live easy."
strtab  5  "The future is now. Join us."
strtab  6  "There is no I in team. But there is in severance."
strtab  7  "We're not just a company. We're a movement."
strtab  8  "Success is a journey, not a destination."
strtab  9  "Innovation starts with you."
strtab  10 "Welcome to the beginning of something great."