strtab  0     "ENGLISH"
strtab  1     "The end of the world is our playground."
strtab  2     "The company is family. The family is the company."
strtab  3     "Escape the mundane. Embrace the extraordinary."
strtab  4     "Work hard, live easy."
strtab  5     "The future is now. Join us."
strtab  6     "There is no I in team. But there is in severance."
strtab  7     "We're not just a company. We're a movement."
strtab  8     "Success is a journey, not a destination."
strtab  9     "Innovation starts with you."
strtab  10    "Welcome to the beginning of something great."
strtab  100   "DUTCH"
strtab  101   "Het einde van de wereld is onze speeltuin."
strtab  102   "Het bedrijf is familie. De familie is het bedrijf."
strtab  103   "Ontsnap aan het alledaagse. Omarm het buitengewone."
strtab  104   "Hard werken, makkelijk leven."
strtab  105   "De toekomst is nu. Doe met ons mee."
strtab  106   "Er is geen ik in team. Maar wel in ontslagvergoeding."
strtab  107   "We zijn niet alleen een bedrijf. We zijn een beweging."
strtab  108   "Succes is een reis, geen bestemming."
strtab  109   "Innovatie begint bij jou."
strtab  110   "Welkom bij het begin van iets groots."

